-- MySQL Script generated by MySQL Workbench
-- 13 febrero 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

/*

se agrega campo de id usuario del ldap pra RVD_USUARIO, la linea está comentada
se agrega campo id_regulacion para RVD_ENCUESTA_SATISFACCION, la linea está comentada

*/

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema reguladomiciliarias
-- -----------------------------------------------------
-- DROP SCHEMA IF EXISTS `reguladomiciliarias` ;

-- -----------------------------------------------------
-- Schema reguladomiciliarias
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `reguladomiciliarias` DEFAULT CHARACTER SET utf8 ;
USE `reguladomiciliarias` ;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_AUTORIDAD_ORDENA_INSPECCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_AUTORIDAD_ORDENA_INSPECCION` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_AUTORIDAD_ORDENA_INSPECCION` (
  `id_autoridad_ordena_inspeccion` INT NOT NULL,
  `nombre_autoridad` VARCHAR(400) NULL DEFAULT NULL,
  `horario_atencion` VARCHAR(400) NULL DEFAULT NULL,
  `calle` VARCHAR(400) NULL DEFAULT NULL,
  `numero_exterior` VARCHAR(100) NULL DEFAULT NULL,
  `numero_interior` VARCHAR(100) NULL DEFAULT NULL,
  `colonia` VARCHAR(400) NULL DEFAULT NULL,
  `demarcacion_municipio` VARCHAR(400) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(6) NULL DEFAULT NULL,
  `ciudad` VARCHAR(400) NULL DEFAULT NULL,
  `telefono` VARCHAR(100) NULL DEFAULT NULL,
  `correo_electronico` VARCHAR(100) NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo',
  PRIMARY KEY (`id_autoridad_ordena_inspeccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_BITACORA_MOVIMIENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_BITACORA_MOVIMIENTO` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_BITACORA_MOVIMIENTO` (
  `id_bitacora_movimiento` INT NOT NULL,
  `subsistema` INT NULL DEFAULT NULL COMMENT 'identificador que indica si es de Regulaciones, Visitas (inpsecciones) o Visitadores (verificadores)',
  `id_registro` INT NULL DEFAULT NULL COMMENT 'id del registro de la cédula (Regulación, Inspección, Verificador)',
  `folio` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Folio de la Regulación o Inspección o Verificador',
  `id_usuario` INT NULL DEFAULT NULL,
  `fecha_evento` DATETIME NULL DEFAULT NULL COMMENT 'Fecha de cuando secede el evento (creación, modificación, eliminación)',
  `id_cat_accion_realizada` INT NULL DEFAULT NULL COMMENT 'FK, llave foránea al catalogo general (cat_genenal)',
  `comentario_rechazo` VARCHAR(400) NULL DEFAULT NULL,
  `campo_modificado` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'se registran los campos afectados separados por punto y coma',
  PRIMARY KEY (`id_bitacora_movimiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_DERECHO_SUJETO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_DERECHO_SUJETO` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_DERECHO_SUJETO` (
  `id_derecho_sujeto` INT NOT NULL,
  `id_inspeccion` INT NULL DEFAULT NULL,
  `descripcion_derecho` VARCHAR(1000) NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',
  PRIMARY KEY (`id_derecho_sujeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_DIRIDO_A`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_DIRIGIDO_A` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_DIRIGIDO_A` (
  `id_dirigido_a` INT NOT NULL,
  `id_inspeccion` INT NOT NULL COMMENT 'Llave foránea que referencia al id de la inspección.',
  `id_cat_dirigido_a` INT NULL DEFAULT NULL COMMENT 'Llave foránea que referencia al catálogo de catálogos, donde obtiene el identificador del concepto \\\"dirigido a\\\"',
  `especifica_otro` VARCHAR(1000) NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',
  PRIMARY KEY (`id_dirigido_a`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_FACULTAD_INSPECTOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_FACULTAD_INSPECTOR` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_FACULTAD_INSPECTOR` (
  `id_facultad_inspector` INT NOT NULL,
  `id_inspeccion` INT NOT NULL COMMENT 'Llave foránea que referencia al id de la inspección',
  `descripcion_facultad` VARCHAR(4000) NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',  
  PRIMARY KEY (`id_facultad_inspector`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_FORMATO_INSPECCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_FORMATO_INSPECCION` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_FORMATO_INSPECCION` (
  `id_formato_inspeccion` INT NOT NULL,
  `id_inspeccion` INT NOT NULL COMMENT 'Lave foránea que referencia al id de la inspección',
  `url_formato` VARCHAR(400) NULL DEFAULT NULL COMMENT 'url de la carpeta donde se depositará el formato',
  `nombre_formato` VARCHAR(400) NULL DEFAULT NULL,
  `tipo_archivo` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Especificar extensión del archivo: pdf, word, excel.',
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',  
  PRIMARY KEY (`id_formato_inspeccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_FUNDAMENTO_JURIDICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_FUNDAMENTO_JURIDICO` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_FUNDAMENTO_JURIDICO` (
  `id_fundamento_juridico` INT NOT NULL,
  `id_inspeccion` INT NOT NULL COMMENT 'Llave foránea que referencia al id de la cedula inspección',
  `id_regulacion` INT NULL DEFAULT NULL COMMENT 'Llave foránea al catálogo de catálogos que contiene el id del catálogo de regulaciones.',
  `id_cat_tipo_fundamento_juridico` INT NULL DEFAULT NULL COMMENT 'Clave del tipo de fundamento:\n1. Cédula inspección\n2. Debe cumplir sujeto\n3. Derecho\n4. Facultad Inspector\n5. Formato\n6. Obligación Sujeto\n7. Origen\n8. Pasos\n9. Requisito Documento\n10. Sanción\n11. Trámite, Servicio, Inspección',
  `id_seccion_cedula` INT NULL DEFAULT NULL COMMENT 'Llave foránea referencia al id de la sección a la que pertenece el fundamento jurídico\n(\nDebe cumplir sujeto\nDerecho\nFacultad Inspector\nFormato\nObligación Sujeto\nOrigen\nPasos\nRequisito Documento\nSanción\nTrámite, Servicio, Inspección\n)',
  `articulo` VARCHAR(1000) NULL DEFAULT NULL,
  `fraccion` VARCHAR(1000) NULL DEFAULT NULL,
  `inciso` VARCHAR(1000) NULL DEFAULT NULL,
  `parrafo` VARCHAR(1000) NULL DEFAULT NULL,
  `numero` VARCHAR(1000) NULL DEFAULT NULL,
  `letra` VARCHAR(1000) NULL DEFAULT NULL,
  `otro` VARCHAR(1000) NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',  
  PRIMARY KEY (`id_fundamento_juridico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_INSPECCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_INSPECCION` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_INSPECCION` (
  `id_inspeccion` INT NOT NULL,
  `homoclave` VARCHAR(50) NOT NULL COMMENT 'La homoclave es el folio de la cédula de inspección',
  `modalidad` VARCHAR(50) NULL DEFAULT NULL,
  `nombre_inspeccion` VARCHAR(1000) NULL DEFAULT NULL,
  `objetivo_inspeccion` VARCHAR(1000) NULL DEFAULT NULL,
  `id_cat_periodicidad` INT NULL DEFAULT NULL,
  `informacion_adicional` VARCHAR(10000) NULL DEFAULT NULL,
  `num_inspecciones_realizadas` INT NULL DEFAULT NULL,
  `numero_inspecciones_sancionadas` INT NULL DEFAULT NULL,
  `ley_fomento_confianza` INT NULL DEFAULT NULL COMMENT '¿La inspección, verificación o visita domiciliaria se encuentra exenta de la Ley de Fomento a la Confianza Ciudadana? SI, NO',
  `justificacion_ley_fomento` VARCHAR(1000) NULL DEFAULT NULL,
  `id_autoridad_ordena_inspeccion` INT NULL DEFAULT NULL COMMENT 'id_autoridad_ordena_inspeccion',
  `palabras_clave` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Palabras clave que describan o identifiquen las inspecciones, verificaciones y visitas domiciliarias',
  `id_cat_tamanio_empresa_inspeccion` INT NULL DEFAULT NULL COMMENT 'Tamaño de empresa por número de trabajadores a la que va dirigida la inspección\n(catálogo)',
  `criterio_inspeccion` VARCHAR(1000) NULL DEFAULT NULL,
  `objeto_sujeto_inspeccion` VARCHAR(1000) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NULL DEFAULT NULL,
  `fecha_modificacion` DATETIME NULL DEFAULT NULL,
  `fecha_publicacion` DATETIME NULL DEFAULT NULL,
  `fecha_publicacion_conamer` DATETIME NULL DEFAULT NULL,
  `id_conamer` INT NULL DEFAULT NULL COMMENT 'Id del registro de la inspección en el sistema de la conamer',
  `num_visitas` INT NULL DEFAULT NULL COMMENT 'número de visitas a la cédula',
  `version_cedula` INT NULL DEFAULT NULL COMMENT 'número de versión de la cédula de inspección',
  `id_cat_estatus_cedula` INT NULL DEFAULT NULL COMMENT 'FK, catálogo general que contiene:\nCreado,\nEnviado a revisión,\nRevisado,\nRechazado a creado,\nEnviado a publicar,\nRechazado a Revisión,\nPublicado,\nEliminado\n',
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',
  PRIMARY KEY (`id_inspeccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_INSPECCION_DONDE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_INSPECCION_DONDE` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_INSPECCION_DONDE` (
  `id_inspeccion_donde` INT NOT NULL COMMENT 'Llave primaria de la tabla',
  `id_inspeccion` INT NULL DEFAULT NULL COMMENT 'Llave foranea que referencia al id de la cedula de inspección',
  `id_cat_inspeccion_donde` INT NULL DEFAULT NULL COMMENT 'llave foránea a catálogo, valores (\nEn el domicilio o establecimientos de los Sujetos Regulados\nEn las oficinas del Sujeto Obligado\nMedios electrónicos\nOtro\n)\npara cuando es de tipo Otro, se especifica en el campo detalle_otro',
  `especifica_otro` VARCHAR(1000) NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',  
  PRIMARY KEY (`id_inspeccion_donde`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_INSPECCION_ES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_INSPECCION_ES` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_INSPECCION_ES` (
  `id_inspeccion_es` INT NOT NULL,
  `id_inspeccion` INT NULL DEFAULT NULL,
  `id_cat_inspeccion_es` INT NULL DEFAULT NULL COMMENT 'llave foranea a catálogo de catálogos, para obtener identificador de inespeccion_es (\npreventiva, \nreactiva, \nseguimiento\n)',
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',  
  PRIMARY KEY (`id_inspeccion_es`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_INSPECCION_MOTIVO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_INSPECCION_MOTIVO` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_INSPECCION_MOTIVO` (
  `id_inspeccion_motivo` INT NOT NULL,
  `id_inspeccion` INT NULL DEFAULT NULL,
  `id_cat_motivo_inspeccion` INT NULL DEFAULT NULL COMMENT 'Ordinaria\nExtraordinaria\nDe oficio\nA solicitud de parte\nForma parte de un trámite o servicio\nOtro',
  `especifica_otro` VARCHAR(1000) NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',  
  PRIMARY KEY (`id_inspeccion_motivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_INSPECCION_MOTIVO_TRAMITE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_INSPECCION_MOTIVO_TRAMITE` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_INSPECCION_MOTIVO_TRAMITE` (
  `id_inspeccion_motivo_tramite` INT NOT NULL,
  `id_inspeccion` INT NULL DEFAULT NULL,
  `folio_tramite` VARCHAR(50) NULL DEFAULT NULL,
  `nombre_tramite` VARCHAR(1000) NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',  
  PRIMARY KEY (`id_inspeccion_motivo_tramite`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_INSPECCION_RESOLUCION_TRAMITE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_INSPECCION_RESOLUCION_TRAMITE` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_INSPECCION_RESOLUCION_TRAMITE` (
  `id_inspeccion_resolucion_tramite` INT NOT NULL,
  `id_inspeccion` INT NULL DEFAULT NULL,
  `folio_tramite` VARCHAR(50) NULL DEFAULT NULL,
  `descripcion` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Inspección derivada de que hayan recibido la resolución de un trámite, servicio, permiso, licencia, autorización o concesión',
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',  
  PRIMARY KEY (`id_inspeccion_resolucion_tramite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_INSPECCION_TIPO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_INSPECCION_TIPO` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_INSPECCION_TIPO` (
  `id_inspeccion_tipo` INT NOT NULL,
  `id_inspeccion` INT NOT NULL,
  `id_cat_tipo_inspeccion` INT NULL DEFAULT NULL COMMENT 'llave foranea, id catálogo de catálogos (para identificar si se trata de vigilancia, promoción, control, supervisión, corroboración, asistencia, asesoría, otra.',
  `especifica_otro` VARCHAR(1000) NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',  
  PRIMARY KEY (`id_inspeccion_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_INSPECCION_TRAMITE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_INSPECCION_TRAMITE` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_INSPECCION_TRAMITE` (
  `id_inspeccion_tramite` INT NOT NULL,
  `id_inspeccion` INT NULL DEFAULT NULL,
  `folio` VARCHAR(50) NULL DEFAULT NULL COMMENT 'folio del trámite o servicio',
  `descripcion_tramite` VARCHAR(1000) NULL DEFAULT NULL COMMENT 'Descripcion del Trámite o Servicio, que motiva la inspección.\nTrámites, Servicios o Inspecciones que deben presentarse de forma previa a la inspección, verificación o supervisión.',
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_inspeccion_tramite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_INSPECCION_VERIFICADOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_INSPECCION_VERIFICADOR` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_INSPECCION_VERIFICADOR` (
  `id_inspeccion_verificador` INT NOT NULL,
  `id_inspeccion` INT NOT NULL,
  `id_verificador`INT NULL DEFAULT NULL COMMENT 'Llave foranea de la cédula del verificador',
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_inspeccion_verificador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_NO_PUBLICIDAD_DATO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_NO_PUBLICIDAD_DATO` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_NO_PUBLICIDAD_DATO` (
  `id_no_publicidad_dato` INT NOT NULL,
  `id_subsistema` INT NULL DEFAULT NULL,  
  `id_cedula` INT NOT NULL DEFAULT 0,
  `id_cat_no_publicidad_dato` INT NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_no_publicidad_dato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_NO_PUBLICIDAD_DOCUMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_NO_PUBLICIDAD_DOCUMENTO` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_NO_PUBLICIDAD_DOCUMENTO` (
  `id_no_publicidad_documento` INT NOT NULL,
  `id_subsistema` INT NULL DEFAULT NULL,  
  `id_cedula` INT NOT NULL DEFAULT 0,
  `url_documento` VARCHAR(400) NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_no_publicidad_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_OBLIGACION_SUJETO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_OBLIGACION_SUJETO` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_OBLIGACION_SUJETO` (
  `id_obligacion_sujeto` INT NOT NULL,
  `id_inspeccion` INT NULL DEFAULT NULL,
  `decripcion_obligacion` VARCHAR(4000) NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_obligacion_sujeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_PASO_INSPECCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_PASO_INSPECCION` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_PASO_INSPECCION` (
  `id_paso_inspeccion` INT NOT NULL,
  `id_inspeccion` INT NOT NULL COMMENT 'Llave foránea que referencia al id de la cédula de inspección',
  `num_paso` INT NULL DEFAULT NULL,
  `descripcion_paso` VARCHAR(4000) NULL DEFAULT NULL,
  `dias` INT NULL DEFAULT NULL,
  `horas` INT NULL DEFAULT NULL,
  `minutos` INT NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',  
  PRIMARY KEY (`id_paso_inspeccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_REGULACIONES_DEBE_CUMPLIR_SUJETO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_REGULACIONES_DEBE_CUMPLIR_SUJETO` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_REGULACIONES_DEBE_CUMPLIR_SUJETO` (
  `id_regulaciones_debe_cumplir_sujeto` INT NOT NULL,
  `id_inspeccion` INT NULL DEFAULT NULL,
  `descripcion_regulaciones_debe_cuplir_sujeto` VARCHAR(4000) NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_regulaciones_debe_cumplir_sujeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_REQUISITO_DOCUMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_REQUISITO_DOCUMENTO` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_REQUISITO_DOCUMENTO` (
  `id_requisito_documento` INT NOT NULL,
  `id_inspeccion` INT NULL DEFAULT NULL,
  `descripcion_requisito_documento` VARCHAR(4000) NULL DEFAULT NULL,
  `lista_tramites_servicios` VARCHAR(4000) NULL DEFAULT NULL,
  `lista_inspecciones` VARCHAR(4000) NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_requisito_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_SANCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_SANCION` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_SANCION` (
  `id_sancion` INT NOT NULL,
  `id_inspeccion` INT NOT NULL,
  `id_cat_sancion` INT NULL DEFAULT NULL,
  `sancion_otro` VARCHAR(400) NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_sancion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_SITUACION_EMERGENCIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_SITUACION_EMERGENCIA` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_SITUACION_EMERGENCIA` (
  `id_situacion_emergencia` INT NOT NULL,
  `id_subsistema` INT NULL DEFAULT NULL,  
  `id_cedula` INT NOT NULL DEFAULT 0,
  `justificacion` VARCHAR(4000) NULL DEFAULT NULL,
  `url_documento` VARCHAR(400) NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_situacion_emergencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_SUPERIOR_JERARQUICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_SUPERIOR_JERARQUICO` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_SUPERIOR_JERARQUICO` (
  `id_superior_jerarquico` INT NOT NULL,
  `id_conamer` INT NULL DEFAULT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `apellido_paterno` VARCHAR(100) NULL DEFAULT NULL,
  `apellido_materno` VARCHAR(100) NULL DEFAULT NULL,
  `cargo` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(50) NULL DEFAULT NULL,
  `correo_electronico` VARCHAR(100) NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',  
  PRIMARY KEY (`id_superior_jerarquico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_REGULACION_TRAMITE_INSPECCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_REGULACION_TRAMITE_INSPECCION` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_REGULACION_TRAMITE_INSPECCION` (
  `id_regulacion_tramite_inspeccion` INT NOT NULL,
  `id_regulacion` INT NOT NULL,
  `id_inspeccion` INT NULL DEFAULT NULL, 
  `folio_tramite` VARCHAR(100) NULL DEFAULT NULL, 
  `nombre_tramite` VARCHAR(1000) NULL DEFAULT NULL,
  `id_cnmr_tramite` INT NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_regulacion_tramite_inspeccion`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_USUARIO_ROL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_USUARIO_ROL` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_USUARIO_ROL` (
  `id_usuario_rol` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_cat_rol` INT NOT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_usuario_rol` ))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_VERIFICADOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_VERIFICADOR` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_VERIFICADOR` (
  `id_verificador` INT NOT NULL,
  `id_conamer` INT NULL DEFAULT NULL,
  `folio_verificador` VARCHAR(50) NULL DEFAULT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `apellido_paterno` VARCHAR(100) NULL DEFAULT NULL,
  `apellido_materno` VARCHAR(100) NULL DEFAULT NULL,
  `numero_empleado` VARCHAR(45) NULL DEFAULT NULL,
  `foto` MEDIUMBLOB NULL DEFAULT NULL,
  `cargo` VARCHAR(100) NULL DEFAULT NULL,
  `id_unidad_adcripcion` INT NOT NULL COMMENT 'autoridad_encargada_ordena_inspeccion',
  `telefono` VARCHAR(50) NULL DEFAULT NULL,
  `correo_electronico` VARCHAR(100) NULL DEFAULT NULL,
  `vigencia_cargo` DATETIME NULL DEFAULT NULL,
  `fecha_alta` DATETIME NULL DEFAULT NULL,
  `fecha_baja` DATETIME NULL DEFAULT NULL,
  `fecha_reactiva` DATETIME NULL DEFAULT NULL,
  `url_documento_acredita_cargo` VARCHAR(400) NULL DEFAULT NULL,
  `id_superior_jerarquico` INT NOT NULL,
  `num_visitas` INT NULL DEFAULT NULL,
  `id_cat_estatus_cedula` INT NULL DEFAULT NULL COMMENT 'FK, catálogo general que contiene:\nCreado,\nEnviado a revisión,\nRevisado,\nRechazado a creado,\nEnviado a publicar,\nRechazado a Revisión,\nPublicado,\nEliminado\n',  
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_verificador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_ACTIVIDAD_ECONOMICA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_ACTIVIDAD_ECONOMICA` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_ACTIVIDAD_ECONOMICA` (
  `id_actividad_economica` INT NOT NULL,
  `id_regulacion` INT NOT NULL,
  `id_sector` INT NULL DEFAULT NULL,
  `id_subsector` INT NULL DEFAULT NULL,
  `id_rama` INT NULL DEFAULT NULL,
  `id_subrama` INT NULL DEFAULT NULL,
  `id_clase` INT NULL DEFAULT NULL,
  `id_usuario_alta` INT NULL DEFAULT NULL,
  `id_usuario_modificacion` INT NULL DEFAULT NULL,
  `fecha_alta` DATETIME NULL DEFAULT NULL,
  `fecha_modificacion` DATETIME NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_actividad_economica`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_AUTORIDAD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_AUTORIDAD` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_AUTORIDAD` (
  `id_autoridad` INT NOT NULL,
  `id_cat_orden_gobierno` INT NOT NULL,
  `id_cat_entidad` INT NULL DEFAULT NULL,
  `descripcion_entidad` VARCHAR(255) NULL DEFAULT NULL,
  `id_cat_municipio` INT NULL DEFAULT NULL,
  `descripcion_municipio` VARCHAR(255) NULL DEFAULT NULL,  
  `nombre_autoridad` VARCHAR(255) NOT NULL,
  `id_usuario_alta` INT NULL DEFAULT NULL,
  `id_usuario_modificacion` INT NULL DEFAULT NULL,
  `fecha_alta` DATETIME NULL DEFAULT NULL,
  `fecha_modificacion` DATETIME NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_autoridad`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_CARRUSEL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_CARRUSEL` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_CARRUSEL` (
  `id_carrusel` INT NOT NULL,
  `titulo` VARCHAR(400) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `imagen_url` VARCHAR(400) NOT NULL,
  `video_url` VARCHAR(400) NULL DEFAULT NULL,
  `id_cat_tipo_modal` INT NULL DEFAULT NULL,
  `id_usuario_alta` INT NULL DEFAULT NULL,
  `id_usuario_modificacion` INT NULL DEFAULT NULL,
  `fecha_alta` DATETIME NULL DEFAULT NULL,
  `fecha_modificacion` DATETIME NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_carrusel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_CAT_GENERAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_CAT_GENERAL` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_CAT_GENERAL` (
  `id_cat_general` INT NOT NULL,
  `id_cat_padre` INT NULL DEFAULT NULL,
  `id_cat_detalle` INT NULL DEFAULT NULL COMMENT 'campo para Actividad Economica, campo para encuesta de satisfacción 0=pregunta cerrada, 1=pregunta abierta';,  
  `orden` INT NULL DEFAULT NULL,
  `descripcion_detalle` VARCHAR(1000) NULL DEFAULT NULL,
  `id_usuario_alta` INT NULL DEFAULT NULL,
  `fecha_alta` DATETIME NULL DEFAULT NULL,
  `id_cnmr` INT NULL DEFAULT NULL COMMENT 'Id del valor de mastercatalogos de la CONAMER. El campo sirve para mapeo cuando el catálogo es común IFT-CONAMER. No aplica para catálogo exclusivo del IFT',
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_cat_general`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_DIAS_INHABILES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_DIAS_INHABILES` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_DIAS_INHABILES` (
  `id_dia_inhabil` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `fin_de_semana` BIT NOT NULL,
  `id_habil` BIT NULL DEFAULT NULL COMMENT 'Identificador para saber si el día se habilita como hábil, pudiendo sábado o domingo. Falso=No, Verdadero=SI',
  `id_usuario_alta` INT NULL DEFAULT NULL,
  `id_usuario_modificacion` INT NULL DEFAULT NULL,
  `fecha_alta` DATETIME NULL DEFAULT NULL,
  `fecha_modificacion` DATETIME NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_dia_inhabil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_DOCUMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_DOCUMENTO` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_DOCUMENTO` (
  `id_documento` INT NOT NULL,
  `id_cat_doc_subsis` INT NOT NULL COMMENT 'El documento pertenece a: Regulacion, Inspeccion o Visitador',
  `id_cedula` INT NOT NULL COMMENT 'Id de la cedula: Regulacion, Inspeccion o Visitador',
  `id_cat_tipo_archivo` INT NOT NULL COMMENT 'Tipo archivo: doc, docx, xls, xlsx, pdf, csv',  
  `url_documento` VARCHAR(500) NULL DEFAULT NULL,
  `id_documento_descarga` INT NULL COMMENT 'Identificador del documento a descargar o cédula del documento, regulacion (pdf, doc), opinión vinculante (pdf) ',
  `nombre_documento` VARCHAR(400) NULL DEFAULT NULL,
  `nombre_original` VARCHAR(400) NULL DEFAULT NULL,
  `id_usuario_alta` INT NULL DEFAULT NULL,
  `id_usuario_modificacion` INT NULL DEFAULT NULL,
  `fecha_alta` DATETIME NULL DEFAULT NULL,
  `fecha_modificacion` DATETIME NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_ENCUESTA_SATISFACCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_ENCUESTA_SATISFACCION` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_ENCUESTA_SATISFACCION` (
  `id_encuesta_satisfaccion` INT NOT NULL,
  `id_subsistema` INT NULL DEFAULT NULL,
  `id_cedula` INT NULL DEFAULT NULL,
  `respuesta_afirmativa` BIT NOT NULL,
  `respuesta_abierta` VARCHAR(850) NULL DEFAULT NULL,
  `correo_participante` VARCHAR(400) NULL DEFAULT NULL,
  `fecha_alta` DATETIME NULL DEFAULT NULL,
  `id_cat_encuesta` INT NOT NULL COMMENT 'Llave foránea que referencia al catálogo de catálogos, para obtener identificador de la encuesta de calidad.',
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',  
  PRIMARY KEY (`id_encuesta_satisfaccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_INDICE_REGULACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_INDICE_REGULACION` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_INDICE_REGULACION` (
  `id_indice_regulacion` INT NOT NULL,
  `id_regulacion` INT NULL DEFAULT NULL,
  `id_indice_padre` INT NULL DEFAULT NULL,
  `texto` VARCHAR(850) NULL DEFAULT NULL,
  `orden` INT NULL DEFAULT NULL,
  `id_usuario_alta` INT NULL DEFAULT NULL,
  `id_usuario_modificacion` INT NULL DEFAULT NULL,
  `fecha_alta` DATETIME NULL DEFAULT NULL,
  `fecha_modificacion` DATETIME NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_indice_regulacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_PREGUNTAS_FRECUENTES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_PREGUNTAS_FRECUENTES` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_PREGUNTAS_FRECUENTES` (
  `id_pregunta_frecuente` INT NOT NULL,
  `pregunta` VARCHAR(400) NOT NULL,
  `respuesta` VARCHAR(400) NOT NULL,
  `id_usuario_alta` INT NULL DEFAULT NULL,
  `id_usuario_modificacion` INT NULL DEFAULT NULL,
  `fecha_alta` DATETIME NULL DEFAULT NULL,
  `fecha_modificacion` DATETIME NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_pregunta_frecuente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_REG_AUTO_CUMPLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_REG_AUTO_CUMPLE` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_REG_AUTO_CUMPLE` (
  `id_reg_auto_cumple` INT NOT NULL,
  `id_regulacion` INT NOT NULL,
  `id_autoridad_cumple` INT NOT NULL,
  `id_usuario_alta` INT NULL DEFAULT NULL,
  `id_usuario_modificacion` INT NULL DEFAULT NULL,
  `fecha_alta` DATETIME NULL DEFAULT NULL,
  `fecha_modificacion` DATETIME NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_reg_auto_cumple`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_REG_AUTO_EMITE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_REG_AUTO_EMITE` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_REG_AUTO_EMITE` (
  `id_reg_auto_emite` INT NOT NULL,
  `id_regulacion` INT NOT NULL,
  `id_autoridad_emite` INT NOT NULL,
  `id_usuario_alta` INT NULL DEFAULT NULL,
  `id_usuario_modificacion` INT NULL DEFAULT NULL,
  `fecha_alta` DATETIME NULL DEFAULT NULL,
  `fecha_modificacion` DATETIME NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_reg_auto_emite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_REG_VINCULADA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_REG_VINCULADA` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_REG_VINCULADA` (
  `id_reg_vinculada` INT NOT NULL,
  `id_regulacion` INT NOT NULL,
  `id_regulacion_padre` INT NOT NULL,
  `id_usuario_alta` INT NULL DEFAULT NULL,
  `id_usuario_modificacion` INT NULL DEFAULT NULL,
  `fecha_alta` DATETIME NULL DEFAULT NULL,
  `fecha_modificacion` DATETIME NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_reg_vinculada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_REGULACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_REGULACION` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_REGULACION` (
  `id_regulacion` INT NOT NULL,
  `id_conamer` INT NULL DEFAULT NULL,
  `regulacion_ift` BIT NOT NULL,
  `nombre_regulacion` VARCHAR(850) NOT NULL,
  `folio_regulacion` VARCHAR(100) NULL DEFAULT NULL,
  `folio_conamer` VARCHAR(100) NULL DEFAULT NULL,
  `id_cat_ambito_ordenamiento` INT NULL DEFAULT NULL,
  `id_cat_tipo_ordenamiento` INT NULL DEFAULT NULL,
  `fecha_expedicion` DATETIME NULL DEFAULT NULL,
  `fecha_actualizacion` DATETIME NULL DEFAULT NULL,
  `fecha_publicacion` DATETIME NULL DEFAULT NULL,
  `id_usuario_publicacion` INT NULL DEFAULT NULL,
  `fecha_publicacion_conamer` DATETIME NULL DEFAULT NULL,
  `fecha_publicacion_dof` DATETIME NULL DEFAULT NULL,
  `tiene_vigencia` BIT NULL DEFAULT NULL,
  `fecha_vigencia` DATETIME NULL DEFAULT NULL,
  `cumple_regulacion` BIT NULL DEFAULT NULL,
  `objetivo_regulacion` VARCHAR(10000) NULL DEFAULT NULL,
  `existen_materias` BIT NULL DEFAULT NULL,
  `actividad_economica` BIT NULL DEFAULT NULL,
  `enlace_oficial` VARCHAR(400) NULL DEFAULT NULL,
  `opinion_vinculante` VARCHAR(400) NULL DEFAULT NULL,
  `id_cat_tipo_baja` INT NULL DEFAULT NULL,
  `fecha_baja` DATETIME NULL DEFAULT NULL,
  `id_usuario_alta` INT NULL DEFAULT NULL,
  `id_usuario_modificacion` INT NULL DEFAULT NULL,
  `fecha_alta` DATETIME NULL DEFAULT NULL,
  `fecha_modificacion` DATETIME NULL DEFAULT NULL,
  `num_visitas` INT NULL DEFAULT NULL COMMENT 'Campo que funciona como contador del número de visitas a la cédula',
  `version_cedula` INT NULL DEFAULT NULL,
  `id_cat_estatus_cedula` INT NULL DEFAULT NULL COMMENT 'FK, catálogo general que contiene:\nCreado,\nEnviado a revisión,\nRevisado,\nRechazado a creado,\nEnviado a publicar,\nRechazado a Revisión,\nPublicado,\nEliminado\n',
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_regulacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_REGULACION_MATERIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_REGULACION_MATERIA` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_REGULACION_MATERIA` (
  `id_reg_materia` INT NOT NULL,
  `id_regulacion` INT NOT NULL,
  `id_cat_materia` INT NOT NULL,
  `id_usuario_alta` INT NULL DEFAULT NULL,
  `id_usuario_modificacion` INT NULL DEFAULT NULL,
  `fecha_alta` DATETIME NULL DEFAULT NULL,
  `fecha_modificacion` DATETIME NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_reg_materia`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_SESIONES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_SESIONES` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_SESIONES` (
  `id_sesion` INT NOT NULL,
  `id_usuario` INT NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_sesion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_USUARIO` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_USUARIO` (
  `id_usuario` INT NOT NULL,
  `id_cat_unidad_admin` INT NOT NULL,
  `id_usuario_ldap` INT NOT NULL COMMENT 'Id del usuario en directorio activo ldap',
  `nombre_usuario` VARCHAR(100) NULL DEFAULT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `apellido_paterno` VARCHAR(100) NULL DEFAULT NULL,
  `apellido_materno` VARCHAR(100) NULL DEFAULT NULL,
  `correo_electronico` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_registro` DATETIME NULL DEFAULT NULL COMMENT 'Fecha de alta del usuario en el sistema RVD',
  `fecha_alta` DATETIME NULL DEFAULT NULL COMMENT 'Asociado al usuario que creo el registro en la tabla',
  `fecha_modificacion` DATETIME NULL DEFAULT NULL COMMENT 'Asociado al usuario que modificó el registro en la tabla',
  `fecha_baja` DATETIME NULL DEFAULT NULL,
  `recibe_notificaciones` BIT NOT NULL,
  `id_usuario_alta` INT NULL DEFAULT NULL,
  `id_usuario_modificacion` INT NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',    
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_INSPECCION_ESTADISTICA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_INSPECCION_ESTADISTICA` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`RVD_INSPECCION_ESTADISTICA` (
  `id_inspeccion_estadistica` INT NOT NULL,
  `id_inspeccion` INT NOT NULL COMMENT 'Llave foránea que referencia al id de la cédula de inspección',
  `mes` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Mes al que corresponde la estadística: enero a diciembre',
  `numero_inspecciones`INT NULL DEFAULT NULL,
  `anio` INT NULL DEFAULT NULL COMMENT 'Año de la estadística a cuatro posiciones',
  `id_estatus` INT NULL DEFAULT NULL COMMENT 'Estatus del registro\n1=activo, 0=inactivo (borrado lógico)',  
  PRIMARY KEY (`id_inspeccion_estadistica`))
ENGINE = InnoDB;


/* CREACION DE TABLAS DE TRABAJO JSON CONAMER */

-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`CNMR_REGULACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`CNMR_REGULACION` ;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`CNMR_REGULACION` (
	`pk_cnmr_regulacion` INT NOT NULL AUTO_INCREMENT, 
	`id` INT NULL DEFAULT NULL, 
	`nombre` VARCHAR(850) NULL DEFAULT NULL, 
	`fechaExpedicion` DATETIME NULL DEFAULT NULL, 
	`fechaPublicacion` DATETIME NULL DEFAULT NULL, 
	`fechaActualizacion` DATETIME NULL DEFAULT NULL, 
	`tienVigencia` BIT NULL DEFAULT NULL, 
	`vigencia_CatId` INT NULL DEFAULT NULL, 
	`unidadVigencia` DATETIME NULL DEFAULT NULL, 
	`aplicaTodosSujetosObligados` BIT NULL DEFAULT NULL, 
	`ambito_CatId` INT NULL DEFAULT NULL, 
	`fechaActualizacionRegulacion` DATETIME NULL DEFAULT NULL, 
	`tipoOrdenamiento_CatId` INT NULL DEFAULT NULL, 
	`indiceRegulacion` TEXT(10000) NULL DEFAULT NULL, 
	`objetivoRegulacion` TEXT(10000) NULL DEFAULT NULL, 
	`usuarioId` INT NULL DEFAULT NULL, 
	`tipoSujetoObligado_CatId` INT NULL DEFAULT NULL, 
	`anexoRegulacion` VARCHAR(350) NULL DEFAULT NULL, 
	`nota` VARCHAR(850) NULL DEFAULT NULL, 
	`preregistro` BIT NULL DEFAULT NULL, 
	`fechaPreregistro` DATETIME NULL DEFAULT NULL, 
	`activo` BIT NULL DEFAULT NULL, 
	`fechaCreacion` DATETIME NULL DEFAULT NULL, 
	`fechaModificacion` DATETIME NULL DEFAULT NULL, 
	`aplicaTodosMaterias` BIT NULL DEFAULT NULL, 
	`homoclave` VARCHAR(100) NULL DEFAULT NULL, 
	`sujetoObligadoID` INT NULL DEFAULT NULL, 
	`url` TEXT(10000) NULL DEFAULT NULL, 
	`documentoPdf` TEXT(10000) NULL DEFAULT NULL, 
	`existenMaterias` BIT NULL DEFAULT NULL, 
	`cumplirRegulacion` BIT NULL DEFAULT NULL, 
	`publico` BIT NULL DEFAULT NULL, 
	`fechaPublico` DATETIME NULL DEFAULT NULL, 
	`usuarioIdPublico` INT NULL DEFAULT NULL, 
	`sujetoObligadoIdPublico` INT NULL DEFAULT NULL, 
	`catCatalogoId` INT NULL DEFAULT NULL, 
	`fechaRecepcion` DATETIME NULL DEFAULT NULL, 
	`actividadEconomica` BIT NULL DEFAULT NULL, 
	`documentoPdfExtension` VARCHAR(1) NULL DEFAULT NULL, 
	`renar_SectorEconomico` VARCHAR(1) NULL DEFAULT NULL, 
	`renarSujetoObligadoAsociado` VARCHAR(1) NULL DEFAULT NULL, 
	`renarRegulacionAsociada` VARCHAR(1) NULL DEFAULT NULL, 
	`renarInspeccionAsociada` VARCHAR(1) NULL DEFAULT NULL, 
	`renarMaterias` VARCHAR(1) NULL DEFAULT NULL, 
	`renar_Indices` VARCHAR(1) NULL DEFAULT NULL, 
	`ambitoDescripcionCat` VARCHAR(1) NULL DEFAULT NULL, 
	`vigenciaDescripcionCat` VARCHAR(1) NULL DEFAULT NULL, 
	`tipoOrdenamientoDescripcionCat` VARCHAR(1) NULL DEFAULT NULL, 
	`renarTramiteAsociada` VARCHAR(1) NULL DEFAULT NULL, 
	`totalesEncuesta` VARCHAR(1) NULL DEFAULT NULL, 
	`entidad` VARCHAR(1) NULL DEFAULT NULL, 
	`municipio` VARCHAR(1) NULL DEFAULT NULL,
	`cod` INT NULL DEFAULT NULL,
 PRIMARY KEY (`pk_cnmr_regulacion`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`CNMR_INDICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`CNMR_INDICE`;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`CNMR_INDICE` (
	`pk_cnmr_indice` INT NOT NULL AUTO_INCREMENT,
	`id` INT NULL DEFAULT NULL, 
	`renarId` INT NULL DEFAULT NULL, 
	`idPadre` INT NULL DEFAULT NULL, 
	`texto` TEXT(10000) NULL DEFAULT NULL, 
	`orden` INT NULL DEFAULT NULL, 
	`activo` BIT NULL DEFAULT NULL, 
	`fechaCreacion` DATETIME NULL DEFAULT NULL, 
	`fechaModificacion` DATETIME NULL DEFAULT NULL, 
	`regulaciones` VARCHAR(1) NULL DEFAULT NULL, 
	`cod` INT NULL DEFAULT NULL,
 PRIMARY KEY (`pk_cnmr_indice`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`CNMR_MATERIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`CNMR_MATERIA`;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`CNMR_MATERIA` (
	`pk_cnmr_materia` INT NOT NULL AUTO_INCREMENT,
	`id` INT NULL DEFAULT NULL, 
	`materia_CatId` INT NULL DEFAULT NULL, 
	`renarId` INT NULL DEFAULT NULL, 
	`usuarioId` INT NULL DEFAULT NULL, 
	`activo` BIT NULL DEFAULT NULL, 
	`fecha` DATETIME NULL DEFAULT NULL, 
	`otra` VARCHAR(850) NULL DEFAULT NULL, 
	`excepcion` BIT NULL DEFAULT NULL, 
	`fechaCreacion` DATETIME NULL DEFAULT NULL, 
	`fechaModificacion` DATETIME NULL DEFAULT NULL, 
	`regulaciones` VARCHAR(1) NULL DEFAULT NULL, 
	`tipoDescripcionCat` VARCHAR(1) NULL DEFAULT NULL, 
	`cod` INT NULL DEFAULT NULL,
 PRIMARY KEY (`pk_cnmr_materia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`CNMR_SECTOR_ECONOMICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`CNMR_SECTOR_ECONOMICO`;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`CNMR_SECTOR_ECONOMICO` (
	`pk_cnmr_sector_economico` INT NOT NULL AUTO_INCREMENT,
	`id` INT NULL DEFAULT NULL, 
	`sector_ScianId` INT NULL DEFAULT NULL, 
	`subsector_ScianId` INT NULL DEFAULT NULL, 
	`rama_ScianId` INT NULL DEFAULT NULL, 
	`subrama_ScianId` INT NULL DEFAULT NULL, 
	`clase_ScianId` INT NULL DEFAULT NULL, 
	`renarId` INT NULL DEFAULT NULL, 
	`usuarioId` INT NULL DEFAULT NULL, 
	`fecha` DATETIME NULL DEFAULT NULL, 
	`activo` BIT NULL DEFAULT NULL, 
	`fechaCreacion` DATETIME NULL DEFAULT NULL, 
	`fechaModificacion` DATETIME NULL DEFAULT NULL, 
	`regulaciones` VARCHAR(1) NULL DEFAULT NULL,
	`cod` INT NULL DEFAULT NULL,	
 PRIMARY KEY (`pk_cnmr_sector_economico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`CNMR_AUTORIDAD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`CNMR_AUTORIDAD`;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`CNMR_AUTORIDAD` (
	`pk_cnmr_autoridad` INT NOT NULL AUTO_INCREMENT,
	`id` INT NULL DEFAULT NULL, 
	`renarId` INT NULL DEFAULT NULL, 
	`sujetoObligadoId` INT NULL DEFAULT NULL, 
	`orden` INT NULL DEFAULT NULL, 
	`tipo` VARCHAR(8000) NULL DEFAULT NULL, 
	`activo` BIT NULL DEFAULT NULL, 
	`fechaCreacion` DATETIME NULL DEFAULT NULL, 
	`fechaModificacion` DATETIME NULL DEFAULT NULL, 
	`master_dependencias` VARCHAR(1) NULL DEFAULT NULL, 
	`regulaciones` VARCHAR(1) NULL DEFAULT NULL, 
	`cod` INT NULL DEFAULT NULL,	
 PRIMARY KEY (`pk_cnmr_autoridad`))	
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`CNMR_REGU_TRAMITE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`CNMR_REGU_TRAMITE`;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`CNMR_REGU_TRAMITE` (
	`pk_cnmr_regu_tramite` INT NOT NULL AUTO_INCREMENT,
	`id` INT NULL DEFAULT NULL, 
	`idTramite` INT NULL DEFAULT NULL, 
	`fechaCreacion` DATETIME NULL DEFAULT NULL, 
	`fechaModificacion` DATETIME NULL DEFAULT NULL, 
	`activo` BIT NULL DEFAULT NULL, 
	`idRenavid` INT NULL DEFAULT NULL, 
	`cod` INT NULL DEFAULT NULL,	
 PRIMARY KEY (`pk_cnmr_regu_tramite`))	
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`CNMR_REGU_INSPECCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`CNMR_REGU_INSPECCION`;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`CNMR_REGU_INSPECCION` (
	`pk_cnmr_regu_inspeccion` INT NOT NULL AUTO_INCREMENT,
	`id` INT NULL DEFAULT NULL, 
	`renarId` INT NULL DEFAULT NULL, 
	`inspeccionIdAsociada` INT NULL DEFAULT NULL, 
	`activo` BIT NULL DEFAULT NULL, 
	`fechaCreacion` DATETIME NULL DEFAULT NULL, 
	`fechaModificacion` DATETIME NULL DEFAULT NULL, 
	`regulaciones` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_inspecciones` VARCHAR(1) NULL DEFAULT NULL, 
 	`cod` INT NULL DEFAULT NULL, 
 PRIMARY KEY (`pk_cnmr_regu_inspeccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`CNMR_REGULACION_VINCULADA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`CNMR_REGULACION_VINCULADA`;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`CNMR_REGULACION_VINCULADA` (
	`pk_cnmr_regulacion_vinculada` INT NOT NULL AUTO_INCREMENT,
	`id` INT NULL DEFAULT NULL, 
	`renarId` INT NULL DEFAULT NULL, 
	`renarIdAsociado` INT NULL DEFAULT NULL, 
	`activo` BIT NULL DEFAULT NULL, 
	`fechaCreacion` DATETIME NULL DEFAULT NULL, 
	`fechaModificacion` DATETIME NULL DEFAULT NULL, 
	`regulaciones` VARCHAR(1) NULL DEFAULT NULL, 
 	`cod` INT NULL DEFAULT NULL, 
 PRIMARY KEY (`pk_cnmr_regulacion_vinculada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`CNMR_INSPECCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`CNMR_INSPECCION`;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`CNMR_INSPECCION` (
	`pk_cnmr_inspeccion` INT NOT NULL AUTO_INCREMENT,
	`id` INT NULL DEFAULT NULL, 
	`nombre` TEXT(10000) NULL DEFAULT NULL, 
	`modalidad` TEXT(10000) NULL DEFAULT NULL, 
	`sujetoObligado_Id` INT NULL DEFAULT NULL, 
	`confianzaCiuda` BIT NULL DEFAULT NULL, 
	`confianzaCiudaJustificacion` TEXT(10000) NULL DEFAULT NULL, 
	`inspeccion_es_catId` INT NULL DEFAULT NULL, 
	`objetivoInspeccion` TEXT(10000) NULL DEFAULT NULL, 
	`periodicidad_catId` INT NULL DEFAULT NULL, 
	`tamanoEmpresa_catId` INT NULL DEFAULT NULL, 
	`existeCriterio` BIT NULL DEFAULT NULL, 
	`describaCriterio` TEXT(10000) NULL DEFAULT NULL, 
	`seInspeccionaSujetoResolucion` BIT NULL DEFAULT NULL, 
	`existeFJOrigenInspeccion` BIT NULL DEFAULT NULL, 
	`bien_elemento_obj` TEXT(10000) NULL DEFAULT NULL, 
	`otros_SO_participan` BIT NULL DEFAULT NULL, 
	`participacionOtrosSOFundamentoFJ` BIT NULL DEFAULT NULL, 
	`firmaFormato` BIT NULL DEFAULT NULL, 
	`formatoFundamentado` BIT NULL DEFAULT NULL, 
	`tieneCostoPagoDerechos` BIT NULL DEFAULT NULL, 
	`indicaMonto_catId` INT NULL DEFAULT NULL, 
	`sancionesFundamentadas` BIT NULL DEFAULT NULL, 
	`multaMontoFijoCalculado` VARCHAR(50) NULL DEFAULT NULL, 
	`montoFijo` DECIMAL(9,0) NULL DEFAULT NULL, 
	`rangoMontoInicial` DECIMAL(9,0) NULL DEFAULT NULL, 
	`rangoMontoFinal` DECIMAL(9,0) NULL DEFAULT NULL, 
	`metodologiaMonto` TEXT(10000) NULL DEFAULT NULL, 
	`montoFundamentadoJurid` BIT NULL DEFAULT NULL, 
	`pasosFundamentadosJuridicamente` BIT NULL DEFAULT NULL, 
	`avisaPreviamenteAlSujetoRegulado` BIT NULL DEFAULT NULL, 
	`valorPlazoAvisarSujetoObligado` INT NULL DEFAULT NULL, 
	`unidadMedida_catId` INT NULL DEFAULT NULL, 
	`multaOpciones_catId` INT NULL DEFAULT NULL, 
	`multaMontoFijo` DECIMAL(9,0) NULL DEFAULT NULL, 
	`multaRangoIncial` DECIMAL(9,0) NULL DEFAULT NULL, 
	`multaRangoFinal` DECIMAL(9,0) NULL DEFAULT NULL, 
	`multaMotodologia` TEXT(10000) NULL DEFAULT NULL, 
	`multaFundamentado` BIT NULL DEFAULT NULL, 
	`preregistro` BIT NULL DEFAULT NULL, 
	`fechaPreregistro` DATETIME NULL DEFAULT NULL, 
	`activo` BIT NULL DEFAULT NULL, 
	`fechaCreacion` DATETIME NULL DEFAULT NULL, 
	`fechaModificacion` DATETIME NULL DEFAULT NULL, 
	`sePuedeQuejar` BIT NULL DEFAULT NULL, 
	`inspeccionesDeSanciones` INT NULL DEFAULT NULL, 
	`codigo` VARCHAR(50) NULL DEFAULT NULL, 
	`renavidTelefonoQuejas` TEXT(10000) NULL DEFAULT NULL, 
	`renavidExtensionQuejas` TEXT(10000) NULL DEFAULT NULL, 
	`renavidCorreoQuejas` TEXT(10000) NULL DEFAULT NULL, 
	`renavidDireccionQuejas` TEXT(10000) NULL DEFAULT NULL, 
	`inspeccionesSeRealizanATravesDe_CatId` INT NULL DEFAULT NULL, 
	`seOtorgaPermiso` BIT NULL DEFAULT NULL, 
	`estatus` INT NULL DEFAULT NULL, 
	`tipoMontoCatId` INT NULL DEFAULT NULL, 
	`montoOtro` TEXT(10000) NULL DEFAULT NULL, 
	`tipomultaMontoCatId` INT NULL DEFAULT NULL, 
	`multaMontoOtro` TEXT(10000) NULL DEFAULT NULL, 
	`renavidDireccionOic` TEXT(10000) NULL DEFAULT NULL, 
	`renavidTelefonoOic` TEXT(10000) NULL DEFAULT NULL, 
	`renavidExtensionOic` TEXT(10000) NULL DEFAULT NULL, 
	`renavidCorreoOic` TEXT(10000) NULL DEFAULT NULL, 
	`inspeccionesSancion` INT NULL DEFAULT NULL, 
	`esSituacionEmergencia` BIT NULL DEFAULT NULL, 
	`descripcionEmergencia` TEXT(10000) NULL DEFAULT NULL, 
	`documentoEmergencia` TEXT(10000) NULL DEFAULT NULL, 
	`permitirDatosPublicos` BIT NULL DEFAULT NULL, 
	`documentoDatosPrivado` TEXT(10000) NULL DEFAULT NULL, 
	`unidadAdministrativaId` INT NULL DEFAULT NULL, 
	`publico` BIT NULL DEFAULT NULL, 
	`fechaPublico` DATETIME NULL DEFAULT NULL, 
	`usuarioIdPublico` INT NULL DEFAULT NULL, 
	`sujetoObligadoIdPublico` INT NULL DEFAULT NULL, 
	`fechaRecepcion` DATETIME NULL DEFAULT NULL, 
	`guidInspeccion` INT NULL DEFAULT NULL, 
	`tipoOperation` VARCHAR(500) NULL DEFAULT NULL, 
	`homoClave` VARCHAR(500) NULL DEFAULT NULL, 
	`renavid_tipoInspeccion` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_dirigido_a` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_dondeSeRealizaIns` VARCHAR(1) NULL DEFAULT NULL, 
	`etiquetas` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_motivacion` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_ContactoAutoridadCompetenteInspecc` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_Materias` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_Sanciones` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_Facultades` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_UnidadesVerificadoras` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_adjuntos` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_pasosRealizar` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_Inspectores` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_SujetoObligado_Inspeccion` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_Estadisticas` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_derechosDelSujetoO` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_obligacionesCumplir` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_requisitos` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_SectorEconomico` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_EsInspeccion` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_DatosContacto` VARCHAR(1) NULL DEFAULT NULL, 
	`renarInspeccionAsociada` VARCHAR(1) NULL DEFAULT NULL, 
	`extensionDocEmergencia` VARCHAR(1) NULL DEFAULT NULL, 
	`extensionDocDatosPrivados` VARCHAR(1) NULL DEFAULT NULL, 
	`descripcionSujetoObligado` VARCHAR(1) NULL DEFAULT NULL, 
	`descripcionUnidadAdministrativa` VARCHAR(1) NULL DEFAULT NULL, 
	`tipoMontoCatDescripcion` VARCHAR(1) NULL DEFAULT NULL, 
	`unidadMedidaCatDescripcion` VARCHAR(1) NULL DEFAULT NULL, 
	`tipoMontoCatMultaDescripcion` VARCHAR(1) NULL DEFAULT NULL, 
	`inspeccionesSeRealizanATravesDe_CatIdDescripcion` VARCHAR(1) NULL DEFAULT NULL, 
	`localizacion` VARCHAR(1) NULL DEFAULT NULL, 
	`periocidadDescripcion` VARCHAR(1) NULL DEFAULT NULL, 
	`tipoSujetoCatId` VARCHAR(1) NULL DEFAULT NULL, 
	`sujetoObligado` VARCHAR(1) NULL DEFAULT NULL, 
	`nivelGobiernoDescripcion` VARCHAR(1) NULL DEFAULT NULL, 
	`tamanoEmpresaDescripcion` VARCHAR(1) NULL DEFAULT NULL, 
	`direccion` VARCHAR(1) NULL DEFAULT NULL, 
	`telefono` VARCHAR(1) NULL DEFAULT NULL, 
	`correo` VARCHAR(1) NULL DEFAULT NULL, 
 	`cod` INT NULL DEFAULT NULL,  
 PRIMARY KEY (`pk_cnmr_inspeccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`CNRM_INSPECCION_TIPO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`CNRM_INSPECCION_TIPO`;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`CNRM_INSPECCION_TIPO` (
	`pk_cnmr_inspeccion_tipo` INT NOT NULL AUTO_INCREMENT,
	`id` INT NULL DEFAULT NULL, 
	`inspeccionTipo_catId` INT NULL DEFAULT NULL, 
	`otro` VARCHAR(3550) NULL DEFAULT NULL, 
	`inspeccionId` INT NULL DEFAULT NULL, 
	`activo` BIT NULL DEFAULT NULL, 
	`fechaCreacion` DATETIME NULL DEFAULT NULL, 
	`fechaModificacion` DATETIME NULL DEFAULT NULL, 
	`descripcionTipo` VARCHAR(1) NULL DEFAULT NULL, 
 	`cod` INT NULL DEFAULT NULL, 
 PRIMARY KEY (`pk_cnmr_inspeccion_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`CNMR_INSPECCION_ESTADISTICA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`CNMR_INSPECCION_ESTADISTICA`;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`CNMR_INSPECCION_ESTADISTICA` (
	`pk_cnmr_inspeccion_estadistica` INT NOT NULL AUTO_INCREMENT,
	`id` INT NULL DEFAULT NULL, 
	`mes` VARCHAR(50) NULL DEFAULT NULL, 
	`numeroInspecciones` INT NULL DEFAULT NULL, 
	`renavid_InspeccionId` INT NULL DEFAULT NULL, 
	`activo` BIT NULL DEFAULT NULL, 
	`fecha` DATETIME NULL DEFAULT NULL, 
	`fechaModificacion` DATETIME NULL DEFAULT NULL, 
 	`cod` INT NULL DEFAULT NULL, 
 PRIMARY KEY (`pk_cnmr_inspeccion_estadistica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`CNMR_INSPECCION_DIRIGIDA_A`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`CNMR_INSPECCION_DIRIGIDA_A`;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`CNMR_INSPECCION_DIRIGIDA_A` (
	`pk_cnmr_inspeccion_dirigiada_a` INT NOT NULL AUTO_INCREMENT,	
	`id` INT NULL DEFAULT NULL, 
	`tipoPersona_catID` INT NULL DEFAULT NULL, 
	`otro` VARCHAR(1150) NULL DEFAULT NULL, 
	`renavid_inspeccionId` INT NULL DEFAULT NULL, 
	`activo` BIT NULL DEFAULT NULL, 
	`fechaCreacion` DATETIME NULL DEFAULT NULL, 
	`fechaModificacion` DATETIME NULL DEFAULT NULL, 
	`tipoDescripcion` VARCHAR(1) NULL DEFAULT NULL, 
 	`cod` INT NULL DEFAULT NULL, 
 PRIMARY KEY (`pk_cnmr_inspeccion_dirigiada_a`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`CNMR_INSPECCION_ES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`CNMR_INSPECCION_ES`;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`CNMR_INSPECCION_ES` (
	`pk_cnmr_inspeccion_es` INT NOT NULL AUTO_INCREMENT,
	`id` INT NULL DEFAULT NULL, 
	`inspeccionId` INT NULL DEFAULT NULL, 
	`inspeccionEsCatId` INT NULL DEFAULT NULL, 
	`fechaCreacion` DATETIME NULL DEFAULT NULL, 
	`fechaModificacion` DATETIME NULL DEFAULT NULL, 
	`activo` BIT NULL DEFAULT NULL, 
	`tipoDescripcion` VARCHAR(1) NULL DEFAULT NULL, 
 	`cod` INT NULL DEFAULT NULL, 
 PRIMARY KEY (`pk_cnmr_inspeccion_es`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`CNMR_MASTER_USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`CNMR_MASTER_USUARIO`;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`CNMR_MASTER_USUARIO` (
	`pk_cnmr_master_usuario` INT NOT NULL AUTO_INCREMENT,	
	`usuId` INT NULL DEFAULT NULL, 
	`usuNombre` VARCHAR(255) NULL DEFAULT NULL, 
	`usuApPaterno` VARCHAR(255) NULL DEFAULT NULL, 
	`usuApMaterno` VARCHAR(255) NULL DEFAULT NULL, 
	`usuTelefono` VARCHAR(255) NULL DEFAULT NULL, 
	`usuExtension` VARCHAR(255) NULL DEFAULT NULL, 
	`usuEmail` VARCHAR(255) NULL DEFAULT NULL, 
	`usuToken_Confirmacion` VARCHAR(255) NULL DEFAULT NULL, 
	`usuPassword` VARCHAR(255) NULL DEFAULT NULL, 
	`usuProvider` VARCHAR(255) NULL DEFAULT NULL, 
	`usuUid` VARCHAR(255) NULL DEFAULT NULL, 
	`usuOauth_Token` TEXT(10000) NULL DEFAULT NULL, 
	`usuTwitter` VARCHAR(255) NULL DEFAULT NULL, 
	`usuFacebook` VARCHAR(255) NULL DEFAULT NULL, 
	`usuIdDependencia` INT NULL DEFAULT NULL, 
	`usuFecha_Alta` DATETIME NULL DEFAULT NULL, 
	`usuFecha_Modificacion` DATETIME NULL DEFAULT NULL, 
	`usuIdStatusCatalogo` INT NULL DEFAULT NULL, 
	`usuIdRol` INT NULL DEFAULT NULL, 
	`usuIdUnidad` INT NULL DEFAULT NULL, 
	`usuPuesto` VARCHAR(850) NULL DEFAULT NULL, 
	`usuCargo` VARCHAR(850) NULL DEFAULT NULL, 
	`usuTitulo` VARCHAR(80) NULL DEFAULT NULL, 
	`usuPMR` BIT NULL DEFAULT NULL, 
	`fotografia` VARCHAR(10) NULL DEFAULT NULL, 
	`fechaAltaCargo` DATETIME NULL DEFAULT NULL, 
	`claveEmpleado` VARCHAR(300) NULL DEFAULT NULL, 
	`codigo` VARCHAR(100) NULL DEFAULT NULL, 
	`curp` VARCHAR(100) NULL DEFAULT NULL, 
	`autenticacioId` INT NULL DEFAULT NULL, 
	`archivoExtencion` VARCHAR(100) NULL DEFAULT NULL, 
	`domicilio` TEXT(10000) NULL DEFAULT NULL, 
	`esSituacionEmergencia` BIT NULL DEFAULT NULL, 
	`descripcionEmergencia` TEXT(10000) NULL DEFAULT NULL, 
	`documentoEmergencia` TEXT(10000) NULL DEFAULT NULL, 
	`tipoDocEmergencia` VARCHAR(100) NULL DEFAULT NULL, 
	`permitirDatosPublicos` BIT NULL DEFAULT NULL, 
	`documentoDatosPrivado` VARCHAR(1000) NULL DEFAULT NULL, 
	`accesoRenavid` BIT NULL DEFAULT NULL, 
	`estatus` INT NULL DEFAULT NULL, 
	`accesoRFTS` BIT NULL DEFAULT NULL, 
	`accesoPMR` BIT NULL DEFAULT NULL, 
	`accesoRenar` BIT NULL DEFAULT NULL, 
	`fechaRecepcion` DATETIME NULL DEFAULT NULL, 
	`homoClave` VARCHAR(500) NULL DEFAULT NULL, 
	`notificacion` BIT NULL DEFAULT NULL, 
	`tablaUsuarioPadre` VARCHAR(100) NULL DEFAULT NULL, 
	`idUsuarioPadre` INT NULL DEFAULT NULL, 
	`justificacionBaja` TEXT(10000) NULL DEFAULT NULL, 
	`fechaJustificacionBaja` DATETIME NULL DEFAULT NULL, 
	`idStatusJustificacionBaja` INT NULL DEFAULT NULL, 
	`accesoCertificaciones` BIT NULL DEFAULT NULL, 
	`oficioJustificacion` VARCHAR(1) NULL DEFAULT NULL, 
	`accesoMesaAyuda` VARCHAR(1) NULL DEFAULT NULL, 
	`autenticacion` VARCHAR(1) NULL DEFAULT NULL, 
	`master_dependencias` VARCHAR(1) NULL DEFAULT NULL, 
	`master_unidades_administrativas` VARCHAR(1) NULL DEFAULT NULL, 
	`oicTieneDependencias` VARCHAR(1) NULL DEFAULT NULL, 
	`oic_AtiendeDependencia` VARCHAR(1) NULL DEFAULT NULL, 
	`pc_acepta_protesta_amr` VARCHAR(1) NULL DEFAULT NULL, 
	`setPassword` VARCHAR(1) NULL DEFAULT NULL, 
	`sujetoObligadoDescripcion` VARCHAR(1) NULL DEFAULT NULL, 
	`unidadDescripcion` VARCHAR(1) NULL DEFAULT NULL, 
	`fechaVigencia` VARCHAR(1) NULL DEFAULT NULL, 
 	`cod` INT NULL DEFAULT NULL,
 PRIMARY KEY (`pk_cnmr_master_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`CNMR_USUARIO_INSPECTOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`CNMR_USUARIO_INSPECTOR`;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`CNMR_USUARIO_INSPECTOR` (
	`pk_cnmr_usuario_inspector` INT NOT NULL AUTO_INCREMENT,
	`id` INT NULL DEFAULT NULL, 
	`usuarioId` INT NULL DEFAULT NULL, 
	`vigenciaEncargo` DATETIME NULL DEFAULT NULL, 
	`tieneVigencia` BIT NULL DEFAULT NULL, 
	`documentoAcrediteCargo` TEXT(10000) NULL DEFAULT NULL, 
	`usuarioJefeId` INT NULL DEFAULT NULL, 
	`tablaUsuarioJefe` INT NULL DEFAULT NULL, 
	`fechaCreacion` DATETIME NULL DEFAULT NULL, 
	`fechaModificacion` DATETIME NULL DEFAULT NULL, 
	`archivoExtencion` VARCHAR(160) NULL DEFAULT NULL, 
	`tieneVigenciaCargo` BIT NULL DEFAULT NULL, 
	`usuarioInspectorId` INT NULL DEFAULT NULL, 
	`master_usuarios`  VARCHAR(1) NULL DEFAULT NULL, 
	`master_Usuarios_Inspector` VARCHAR(1) NULL DEFAULT NULL, 
	`masterUsuarioJefe` VARCHAR(1) NULL DEFAULT NULL, 
 	`cod` INT NULL DEFAULT NULL,
 PRIMARY KEY (`pk_cnmr_usuario_inspector`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`CNMR_INSPECCION_INSPECTOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`CNMR_INSPECCION_INSPECTOR`;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`CNMR_INSPECCION_INSPECTOR` (
	`pk_cnmr_inspeccion_inspector` INT NOT NULL AUTO_INCREMENT,
	`id` INT NULL DEFAULT NULL, 
	`renavid_UsurioInspectorId` INT NULL DEFAULT NULL, 
	`activo` BIT NULL DEFAULT NULL, 
	`fecha` DATETIME NULL DEFAULT NULL, 
	`fechaModificacion` DATETIME NULL DEFAULT NULL, 
	`renavid_InspeccionId` INT NULL DEFAULT NULL, 
	`dondeSeRegistro` VARCHAR(50) NULL DEFAULT NULL, 
	`publico` BIT NULL DEFAULT NULL, 
	`fechaPublico` DATETIME NULL DEFAULT NULL, 
	`usuarioIdPublico` INT NULL DEFAULT NULL, 
	`sujetoObligadoIdPublico` INT NULL DEFAULT NULL, 
	`renavid_UsuarioMasterInspectorId` INT NULL DEFAULT NULL, 
	`master_usuarios` VARCHAR(1) NULL DEFAULT NULL, 
	`master_Usuarios_Inspector` VARCHAR(1) NULL DEFAULT NULL, 
	`renavid_inspecciones` VARCHAR(1) NULL DEFAULT NULL, 
	`homoclave` VARCHAR(1) NULL DEFAULT NULL, 
 	`cod` INT NULL DEFAULT NULL,
 PRIMARY KEY (`pk_cnmr_inspeccion_inspector`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`CNMR_CAT_ENDPOINT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`CNMR_CAT_ENDPOINT`;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`CNMR_CAT_ENDPOINT` (
	`pk_cnmr_cat_endpoint` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NULL DEFAULT NULL,
	`endpoint` VARCHAR(1000) NULL DEFAULT NULL,	
	`tipo_ambiente` INT NULL DEFAULT NULL, 
	`estatus` VARCHAR(1) NULL DEFAULT NULL, 
 PRIMARY KEY (`pk_cnmr_cat_endpoint`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`CNMR_CEDULA_PENDIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`CNMR_CEDULA_PENDIENTE`;

CREATE TABLE IF NOT EXISTS `reguladomiciliarias`.`CNMR_CEDULA_PENDIENTE` (
	`pk_cnmr_cedula_pendiente` INT NOT NULL AUTO_INCREMENT,
	`id_subsistema` INT NULL DEFAULT NULL, 
	`id_cedula` INT NULL DEFAULT 0, 
	`folio_homoclave` VARCHAR(100) NULL DEFAULT NULL,
	`descripcion_error` VARCHAR(1000) NULL DEFAULT NULL,	
	`estatus_pendiente` INT NULL DEFAULT NULL, 
 PRIMARY KEY (`pk_cnmr_cedula_pendiente`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `reguladomiciliarias`.`RVD_ENDPOINT_SUBSIST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reguladomiciliarias`.`RVD_ENDPOINT_SUBSIST`;
CREATE TABLE `reguladomiciliarias`.`RVD_ENDPOINT_SUBSIST` (
  `id_endpoint_subsist` int NOT NULL,
  `id_subsistema` int NULL DEFAULT NULL,
  `endpoint` varchar(1000) NULL DEFAULT NULL,
  `id_tipo_ambiente` int NULL DEFAULT NULL,
  `estatus` int NULL DEFAULT NULL,
  PRIMARY KEY (`id_endpoint_subsist`))
ENGINE=InnoDB ;